# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'MatchIt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MatchIt
  platform :ios, '9.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore' 

  target 'MatchItTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MatchIt-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MatchIt-tvOS

  target 'MatchIt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
